name: CI
on:
  push:
    branches: [ slave ]
  pull_request:
    branches: [ slave ]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Fuck reppy
        run: |
          curl -o reppy-0.4.14.tar.gz https://files.pythonhosted.org/packages/b0/b9/8bb8a4cd95dfc6038fb721fad95da8e9558ec936688150302cbd7874c45c/reppy-0.4.14.tar.gz
          tar -xzvf reppy-0.4.14.tar.gz
          rm reppy-0.4.14.tar.gz
          cd reppy-0.4.14/reppy/rep-cpp/deps/url-cpp/include
          sed -i '1i\#include <limits>' punycode.h
          sed -i '1i\#include <stdexcept>' punycode.h
          cd /home/runner/work/sese-engine/sese-engine
          tar -zcvf reppy-0.4.14.tar.gz reppy-0.4.14
          pip install ./reppy-0.4.14.tar.gz
      - name: Install dependencies
        run: |
          pip config set global.index-url https://mirror.sjtu.edu.cn/pypi/web/simple
          pip install -r requirements.txt
      - name: unittest
        run: cd unittest && python ut.py
